version: "3"
services:
  app:
    build: .
    command: /usr/bin/python2.7 -m flask run --host 0.0.0.0 --port 5000
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=True
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/bookmarker
  worker:
    build: .
    command: python -m flask rq worker
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/var/www/bookmarker
  postgres:
    image: "postgres:alpine"
  redis:
    image: "redis:alpine"
